#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PARAMSZ=$@
SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/base/deploy

if [ -f "${CURRENT_DIR}/git_key" ]; then
    echo Installing git ssh Key
    mkdir -p ~/.ssh
    cp -f ${CURRENT_DIR}/git_key ~/.ssh/id_rsa
    chmod 400 ~/.ssh/id_rsa
    echo "StrictHostKeyChecking no" >> ~/.ssh/config
fi

if [ -f "${CURRENT_DIR}/git_hosts" ]; then
    echo Running ssh-keyscan
    for HOST in $(cat ${CURRENT_DIR}/git_hosts); do
        ssh-keyscan $HOST >> ~/.ssh/known_hosts
    done
fi

for DEPLOY_FILE in ${SOURCE_DIR}/deploy-*; do
    echo Running ${DEPLOY_FILE} ${PARAMSZ}
    . ${DEPLOY_FILE} ${PARAMSZ}
done