#!/bin/bash -e

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

for INSTALL_FILE in ${SOURCE_DIR}/python/install-*; do
        echo Running ${INSTALL_FILE}
        source ${INSTALL_FILE}
done